# Process Data from Duke University and GfK's "Measuring Morality" project 

- **Goal**: Place data in format for interactive visualizations in D3.js

- **Dataset Source:** http://kenan.ethics.duke.edu/attitudes/resources/measuring-morality/
- **Codebook Source:** http://kenan.ethics.duke.edu/attitudes/files/2012/08/KN-Morality-Survey-Technical-Report.pdf



-----

# 1) Explore and Subset Data

In [1]:
import pandas as pd
import numpy as np
import csv

# read csv data as pandas dataframe

d = pd.read_csv('/Users/dschan/Downloads/w209_project/python_d3/MMdata_merged.csv')

# check data type and shape

print type(d)
print "shape:", d.shape[0]
print

# select specific columns: weight column, demographic columns, and moral-related columns

d = d[[ 'weight',
        'core_par', 'ppagecat', 'PPETHM', 'PPEDUCAT', 'PPGENDER', 'PPINCCAT', 'PPREG4', 'PPSTATEN',
        'DPES11',
        'EPQ1',
        'I10',
        'IS1','IS6','IS8',
        'L1','L4','L9','L11',
        'MI9',
        'SV3','SV8','SV11','SV12','SV16','SV17','SV18','SV21',
        #'pppa0233',
        #'pphi0047','pphi0048',
        'TET7']]

# view column names 
print "column names:"
print list(d.columns.values)
print

# print example rows

print d.head()

<class 'pandas.core.frame.DataFrame'>
shape: 1519

column names:
['weight', 'core_par', 'ppagecat', 'PPETHM', 'PPEDUCAT', 'PPGENDER', 'PPINCCAT', 'PPREG4', 'PPSTATEN', 'DPES11', 'EPQ1', 'I10', 'IS1', 'IS6', 'IS8', 'L1', 'L4', 'L9', 'L11', 'MI9', 'SV3', 'SV8', 'SV11', 'SV12', 'SV16', 'SV17', 'SV18', 'SV21', 'TET7']

   weight  core_par  ppagecat  PPETHM  PPEDUCAT  PPGENDER  PPINCCAT  PPREG4  \
0    1.05         0         6       1         4         2         3       4
1    2.60         0         2       1         3         1         3       2
2    0.69         1         2       4         2         2         2       4
3    1.74         1         3       1         4         2         4       3
4    2.43         0         3       1         3         2         4       4

   PPSTATEN  DPES11  ...   MI9  SV3  SV8  SV11  SV12  SV16  SV17  SV18  SV21  \
0        81       5  ...     4    4    4     2    -1     1     3     3     4
1        47       5  ...     7    2    1     2     1     5     2     2     2
2        91       3  ...     4    1    5     4     2     1     1     1     5
3        56       6  ...     5    1    2     2     4     2     3     4     4
4        88       6  ...     4    3    3     4     4     3     3     3     3

   TET7
0     3
1     4
2     2
3     5
4     3

[5 rows x 29 columns]

# 2) Add Demographic Dictionaries for Readability

In [2]:
# create demographic dictionaries to later print readable values, not numeric keys

# 'core_par', 'ppagecat', 'PPETHM', 'PPEDUCAT', 'PPGENDER', 'PPINCCAT', 'PPREG4', PPSTATEN'

core_par = {-2: 'Not asked',
            -1: 'Refused',
             0: 'Not Parent',
             1: 'Parent'}

ppagecat = { 1: '18-24',
             2: '25-34',
             3: '35-44',
             4: '45-54',
             5: '55-64',
             6: '65-74',
             7: '75+',
             0: '18-'}

PPETHM = {-2: 'Not asked',
          -1: 'REFUSED',
           1: 'White',
           2: 'Black',
           3: 'Other',
           4: 'Hispanic',
           5: '2+ Races, Non-Hispanic'}

PPEDUCAT = {-2: 'Not asked',
            -1: 'REFUSED',
             1: '11yrs- ',
             2: '12yrs',
             3: '12yrs+',
             4: '16yrs+'}

PPGENDER = {-2: 'Not asked',
            -1: 'REFUSED',
             1: 'Male',
             2: 'Female'}

PPINCCAT = {-2: 'Not asked',
            -1: 'Refused',
             1: '$10K-',
             2: '$10K-49K',
             3: '$50K-75K',
             4: '$75K+'}

PPREG4 = {-2: 'Not asked',
          -1: 'REFUSED',
           1: 'Northeast',
           2: 'Midwest',
           3: 'South',
           4: 'West'}

PPSTATEN = { -2: 'Not asked'
            ,-1: 'REFUSED'
            ,11: 'ME'
            ,12: 'NH' 
            ,13: 'VT' 
            ,14: 'MA' 
            ,15: 'RI' 
            ,16: 'CT' 
            ,21: 'NY' 
            ,22: 'NJ' 
            ,23: 'PA' 
            ,31: 'OH' 
            ,32: 'IN'
            ,33: 'IL' 
            ,34: 'MI' 
            ,35: 'WI' 
            ,41: 'MN' 
            ,42: 'IA' 
            ,43: 'MO' 
            ,44: 'ND' 
            ,45: 'SD' 
            ,46: 'NE' 
            ,47: 'KS' 
            ,51: 'DE' 
            ,52: 'MD' 
            ,53: 'DC' 
            ,54: 'VA' 
            ,55: 'WV' 
            ,56: 'NC' 
            ,57: 'SC' 
            ,58: 'GA' 
            ,59: 'FL' 
            ,61: 'KY' 
            ,62: 'TN' 
            ,63: 'AL' 
            ,64: 'MS' 
            ,71: 'AR' 
            ,72: 'LA' 
            ,73: 'OK' 
            ,74: 'TX' 
            ,81: 'MT' 
            ,82: 'ID' 
            ,83: 'WY' 
            ,84: 'CO'
            ,85: 'NM' 
            ,86: 'AZ' 
            ,87: 'UT' 
            ,88: 'NV' 
            ,91: 'WA' 
            ,92: 'OR' 
            ,93: 'CA' 
            ,94: 'AK' 
            ,95: 'HI' 
            ,96: 'AS' 
            ,97: 'GU' 
            ,98: 'PR' 
            ,99: 'VI'}

print "before update:"
print d['core_par'][:5] 
print

# apply dictionaries to their corresponding columns

d['core_par'] = d['core_par'].apply(lambda x: core_par[x])
d['ppagecat'] = d['ppagecat'].apply(lambda x: ppagecat[x])
d['PPETHM'] = d['PPETHM'].apply(lambda x: PPETHM[x])
d['PPEDUCAT'] = d['PPEDUCAT'].apply(lambda x: PPEDUCAT[x])
d['PPGENDER'] = d['PPGENDER'].apply(lambda x: PPGENDER[x])
d['PPINCCAT'] = d['PPINCCAT'].apply(lambda x: PPINCCAT[x])
d['PPREG4'] = d['PPREG4'].apply(lambda x: PPREG4[x])
d['PPSTATEN'] = d['PPSTATEN'].apply(lambda x: PPSTATEN[x])

# quality check one case

print "after update:"
print d['core_par'][:5] 

'''
print d['ppagecat']
print d['PPETHM'] 
print d['PPEDUCAT'] 
print d['PPGENDER'] 
print d['PPINCCAT']
print d['PPREG4']
print d['PPSTATEN']
'''

before update:
0    0
1    0
2    1
3    1
4    0
Name: core_par, dtype: int64

after update:
0    Not Parent
1    Not Parent
2        Parent
3        Parent
4    Not Parent
Name: core_par, dtype: object

"\nprint d['ppagecat']\nprint d['PPETHM'] \nprint d['PPEDUCAT'] \nprint d['PPGENDER'] \nprint d['PPINCCAT']\nprint d['PPREG4']\nprint d['PPSTATEN']\n"

# 3) Recode Non-Demographic Column Values

In [3]:
# document scales of non-demographic columns of interest

'''
# columns with ascending response options (e.g., 1 = strongly agree)
'EPQ1' (1-7)
'I10' (1-5)
'L1' (1-7)
'SV' (1-7)
'pphi0047','pphi0048' (1-4)

# columns with descending response options (e.g., 7 = strongly disagree)
'DPES11' (1-7)
'IS1','IS6','IS8' (1-5)
'MI9' (1-7)
'TET' (1-5)

# columns that ask respondent to rank top categories
'MOPS11','MOPS12'
'''

# replace negative values with NaN (not a number)

for i in range(9, d.shape[1]):
    
    d[d.columns[i]] = d[d.columns[i]].replace(-1,np.NaN)
    d[d.columns[i]] = d[d.columns[i]].replace(-2,np.NaN)

# define function that, for example, transforms survey value from 1 to 7, 7 to 1, etc., 
# to normalize values across survey questions, where values 1 and 2 are always a yes-type response

# x refers to column, and xmax refers to the max possible value per the survey codebook

def reverse(x, xmax):
    x = xmax + 1 - x
    return x 
    
# invoke reverse function on appropriate columns

d.DPES11 = reverse(d.DPES11, 7)
d.IS1    = reverse(d.IS1, 5)
d.IS6    = reverse(d.IS6, 5)
d.IS8    = reverse(d.IS8, 5)
d.MI9    = reverse(d.MI9, 7)
d.TET7   = reverse(d.TET7, 5)

# store dataframe headers in an object to call this object in print statement later

headers = d.columns.values.tolist()

# loop through non-demographic columns, which start a index 9

for i in range(9, d.shape[1]):
    
    print "before recode:"
    print d[d.columns[i]][:5]
    print
    
    d[d.columns[i]] = d[d.columns[i]].replace(2,1)
    d[d.columns[i]] = d[d.columns[i]].replace(3,0)
    d[d.columns[i]] = d[d.columns[i]].replace(4,0)
    d[d.columns[i]] = d[d.columns[i]].replace(5,0)
    d[d.columns[i]] = d[d.columns[i]].replace(6,0)
    d[d.columns[i]] = d[d.columns[i]].replace(7,0)
    
    print "after recode:"
    print (d[d.columns[i]][:5])
    print

print d.describe()

'''
# comment out subset that removes missing values, and instead hold off until cell below to
# instead invoke on a column-by-column basis and thereby preserve more sample size

d = d.dropna(subset = 
      [ 'weight',
        'core_par', 'ppagecat', 'PPETHM', 'PPEDUCAT', 'PPGENDER', 'PPINCCAT', 'PPREG4', 'PPSTATEN',
        'DPES11',
        'EPQ1',
        'I10',
        'IS1','IS6','IS8',
        'L1','L4','L9','L11',
        'MI9',
        'SV3','SV8','SV11','SV12','SV16','SV17','SV18','SV21',
        #'pppa0233',
        #'pphi0047','pphi0048',
        'TET7'])
        
print d.shape
'''

before recode:
0    3
1    3
2    5
3    2
4    2
Name: DPES11, dtype: float64

after recode:
0    0
1    0
2    0
3    1
4    1
Name: DPES11, dtype: float64

before recode:
0    3
1    1
2    4
3    5
4    4
Name: EPQ1, dtype: float64

after recode:
0    0
1    1
2    0
3    0
4    0
Name: EPQ1, dtype: float64

before recode:
0    3
1    4
2    3
3    3
4    3
Name: I10, dtype: float64

after recode:
0    0
1    0
2    0
3    0
4    0
Name: I10, dtype: float64

before recode:
0    4
1    5
2    5
3    5
4    3
Name: IS1, dtype: float64

after recode:
0    0
1    0
2    0
3    0
4    0
Name: IS1, dtype: float64

before recode:
0    3
1    2
2    2
3    3
4    3
Name: IS6, dtype: float64

after recode:
0    0
1    1
2    1
3    0
4    0
Name: IS6, dtype: float64

before recode:
0    4
1    2
2    4
3    2
4    4
Name: IS8, dtype: float64

after recode:
0    0
1    1
2    0
3    1
4    0
Name: IS8, dtype: float64

before recode:
0    3
1    6
2    6
3    4
4    4
Name: L1, dtype: float64

after recode:
0    0
1    0
2    0
3    0
4    0
Name: L1, dtype: float64

before recode:
0    5
1    7
2    4
3    5
4    5
Name: L4, dtype: float64

after recode:
0    0
1    0
2    0
3    0
4    0
Name: L4, dtype: float64

before recode:
0    4
1    7
2    5
3    7
4    6
Name: L9, dtype: float64

after recode:
0    0
1    0
2    0
3    0
4    0
Name: L9, dtype: float64

before recode:
0    5
1    6
2    5
3    6
4    5
Name: L11, dtype: float64

after recode:
0    0
1    0
2    0
3    0
4    0
Name: L11, dtype: float64

before recode:
0    4
1    1
2    4
3    3
4    4
Name: MI9, dtype: float64

after recode:
0    0
1    1
2    0
3    0
4    0
Name: MI9, dtype: float64

before recode:
0    4
1    2
2    1
3    1
4    3
Name: SV3, dtype: float64

after recode:
0    0
1    1
2    1
3    1
4    0
Name: SV3, dtype: float64

before recode:
0    4
1    1
2    5
3    2
4    3
Name: SV8, dtype: float64

after recode:
0    0
1    1
2    0
3    1
4    0
Name: SV8, dtype: float64

before recode:
0    2
1    2
2    4
3    2
4    4
Name: SV11, dtype: float64

after recode:
0    1
1    1
2    0
3    1
4    0
Name: SV11, dtype: float64

before recode:
0   NaN
1     1
2     2
3     4
4     4
Name: SV12, dtype: float64

after recode:
0   NaN
1     1
2     1
3     0
4     0
Name: SV12, dtype: float64

before recode:
0    1
1    5
2    1
3    2
4    3
Name: SV16, dtype: float64

after recode:
0    1
1    0
2    1
3    1
4    0
Name: SV16, dtype: float64

before recode:
0    3
1    2
2    1
3    3
4    3
Name: SV17, dtype: float64

after recode:
0    0
1    1
2    1
3    0
4    0
Name: SV17, dtype: float64

before recode:
0    3
1    2
2    1
3    4
4    3
Name: SV18, dtype: float64

after recode:
0    0
1    1
2    1
3    0
4    0
Name: SV18, dtype: float64

before recode:
0    4
1    2
2    5
3    4
4    3
Name: SV21, dtype: float64

after recode:
0    0
1    1
2    0
3    0
4    0
Name: SV21, dtype: float64

before recode:
0    3
1    2
2    4
3    1
4    3
Name: TET7, dtype: float64

after recode:
0    0
1    1
2    0
3    1
4    0
Name: TET7, dtype: float64

            weight       DPES11         EPQ1          I10          IS1  \
count  1519.000000  1495.000000  1505.000000  1505.000000  1507.000000
mean      1.000112     0.501672     0.259801     0.497010     0.051095
std       0.734256     0.500165     0.438671     0.500157     0.220264
min       0.140000     0.000000     0.000000     0.000000     0.000000
25%       0.430000     0.000000     0.000000     0.000000     0.000000
50%       0.770000     1.000000     0.000000     0.000000     0.000000
75%       1.380000     1.000000     1.000000     1.000000     0.000000
max       3.560000     1.000000     1.000000     1.000000     1.000000

               IS6          IS8           L1           L4           L9  \
count  1505.000000  1505.000000  1503.000000  1503.000000  1499.000000
mean      0.712292     0.143522     0.079175     0.067199     0.018679
std       0.452845     0.350721     0.270102     0.250450     0.135434
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       1.000000     0.000000     0.000000     0.000000     0.000000
75%       1.000000     0.000000     0.000000     0.000000     0.000000
max       1.000000     1.000000     1.000000     1.000000     1.000000

          ...               MI9          SV3          SV8         SV11  \
count     ...       1499.000000  1502.000000  1498.000000  1494.000000
mean      ...          0.316211     0.633822     0.537383     0.633199
std       ...          0.465151     0.481920     0.498767     0.482093
min       ...          0.000000     0.000000     0.000000     0.000000
25%       ...          0.000000     0.000000     0.000000     0.000000
50%       ...          0.000000     1.000000     1.000000     1.000000
75%       ...          1.000000     1.000000     1.000000     1.000000
max       ...          1.000000     1.000000     1.000000     1.000000

             SV12         SV16         SV17         SV18         SV21  \
count  1492.00000  1496.000000  1504.000000  1493.000000  1494.000000
mean      0.58311     0.467246     0.230718     0.672472     0.325971
std       0.49321     0.499093     0.421432     0.469469     0.468893
min       0.00000     0.000000     0.000000     0.000000     0.000000
25%       0.00000     0.000000     0.000000     0.000000     0.000000
50%       1.00000     0.000000     0.000000     1.000000     0.000000
75%       1.00000     1.000000     0.000000     1.000000     1.000000
max       1.00000     1.000000     1.000000     1.000000     1.000000

              TET7
count  1502.000000
mean      0.701065
std       0.457944
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

[8 rows x 21 columns]

"\n# comment out subset that removes missing values, and instead hold off until cell below to\n# instead invoke on a column-by-column basis and thereby preserve more sample size\n\nd = d.dropna(subset = \n      [ 'weight',\n        'core_par', 'ppagecat', 'PPETHM', 'PPEDUCAT', 'PPGENDER', 'PPINCCAT', 'PPREG4', 'PPSTATEN',\n        'DPES11',\n        'EPQ1',\n        'I10',\n        'IS1','IS6','IS8',\n        'L1','L4','L9','L11',\n        'MI9',\n        'SV3','SV8','SV11','SV12','SV16','SV17','SV18','SV21',\n        #'pppa0233',\n        #'pphi0047','pphi0048',\n        'TET7'])\n        \nprint d.shape\n"

# 4) Weighted averages on dummy data (temp section)

In [4]:
# explore basic example of weighted column, not row, averages in Python

c1 = [.9, .1]
c2 = [.5, .5]

test = pd.DataFrame({'c1': [.7, .1],
                     'c2': [.5, .5]},
                    index = [1, 2])

print "shape:", test.shape
print
print "dataframe:"
print test[:]
print 

print "(0,0):", test.iloc[0][0]
print "(0,1):", test.iloc[0][1]
print "(1,0):", test.iloc[1][0]
print "(1,1):", test.iloc[1][1]
print 

# http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ma.average.html#numpy.ma.average
# purposely place the c2 as the weights, to calculate correctly

print "Manual weighted avg: weighted sum / sum of weights = (0.7*0.5 + 0.1*.05) / (0.5 + 0.5) = 0.4"
print "Python weighted avg:", round(np.average(a=test['c1'], weights=test['c2']),2)

shape: (2, 2)

dataframe:
    c1   c2
1  0.7  0.5
2  0.1  0.5

(0,0): 0.7
(0,1): 0.5
(1,0): 0.1
(1,1): 0.5

Manual weighted avg: weighted sum / sum of weights = (0.7*0.5 + 0.1*.05) / (0.5 + 0.5) = 0.4
Python weighted avg: 0.4

# Documentation: Sample Survey Questions

- DPES11. I develop strong emotions toward people I can rely on.

- EPQ1. Moral standards should be seen as individualistic: what one person considers to be moral
may be judged as immoral by another person.

- IS6. If one believes something is right, one must stand by it, even if it means losing friends or
missing out on profitable opportunities.

- L9. Parents should empower children as much as possible so that they may follow their dreams.

- I10. Spiritually, I consider myself. . . 

-----

# 5) Export Weighted Averages, Grouped by Demographics

In [5]:
# explore weights further, now on some actual survey data 

# multiple column by post-stratification weight, which is important so the sample better reflects the population
# http://www.atlas.illinois.edu/support/stats/resources/spss/create-post-stratification-weights-for-survery-analysis.pdf

'''
d['DPES11_wt'] = d.DPES11 * d.weight
print d.loc[:, ['weight','PPREG4','DPES11','DPES11_wt']][:10]
print

# calculate step-by-step weighted average (which overlooks if NaN exists)
print "1:", d.groupby(['PPREG4', 'PPGENDER']).apply(lambda x: np.sum(x.DPES11*x.weight))
print
print "1:", d.groupby(['PPREG4', 'PPGENDER']).apply(lambda x: np.sum(x.weight))
print
print "1:", d.groupby(['PPREG4', 'PPGENDER']).apply(lambda x: np.sum(x.DPES11*x.weight) / np.sum(x.weight))
print
'''

'''
#temp = pd.DataFrame(d.groupby(['PPREG4', 'PPGENDER']).apply(lambda x: np.sum(x.DPES11*x.weight) / np.sum(x.weight)))
#temp.rename(columns = {0:'Weighted Pct'}, inplace = True)

# calculate with np.average function (which does not overlook if NaN exists) 
# option is to use mask function with np.ma.average, but avoid that after trial
# http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ma.masked_invalid.html

# print "2:", d.groupby(['PPREG4','PPGENDER']).apply(lambda x: np.average(a=x['DPES11'], weights=x['weight'], returned=True))
'''

# create wt_avg function that 
# 1) takes two demographic columns and a list of non-demographic columns,
# 2) scrolls through each non-demographic column to calculate the weighted average,
# 3) and exports data to one csv file per non-demographic column

def wt_avg_2(combo, cnames):
    
    for cname in cnames:
        
        # subset given column to remove its rows with missing values, otherwise np.average runs into issues
        # http://stackoverflow.com/questions/13413590/how-to-drop-rows-of-pandas-dataframe-whose-value-of-certain-column-is-nan
        temp = d.dropna(subset = [cname])
        
        # rename first column of eventual CSV output
        temp.rename(columns={combo: 'Category'}, inplace=True)
                             
        # take the groupby weighted average of given column
        temp = temp.groupby(['Category']).apply(lambda x: np.average(a=x[cname], weights=x['weight']))
        
        # transform back from series to dataframe
        # rename second column of eventual CSV output

        temp = pd.DataFrame(temp, columns=[combo])
        temp.rename(columns={combo: 'Weighted_Pct'}, inplace=True)
        
        print "--------------"
        print "cname:", cname
        print "--------------"
        print temp.shape
        print type(temp)
        print temp
        
        # export results to csv in format for D3.js graphs
        temp.to_csv('/Users/dschan/Downloads/w209_project/python_d3/' + 'z' + 
                    combo + "_" + cname + '.csv', header=True, index=True)
            
# create combo variables

d['PPREG4_core_par'] = d[['PPREG4', 'core_par']].apply(lambda x: ': '.join(x), axis=1)
d['PPREG4_PPEDUCAT'] = d[['PPREG4', 'PPEDUCAT']].apply(lambda x: ': '.join(x), axis=1)
d['PPREG4_PPGENDER'] = d[['PPREG4', 'PPGENDER']].apply(lambda x: ': '.join(x), axis=1)
d['PPREG4_PPINCCAT'] = d[['PPREG4', 'PPINCCAT']].apply(lambda x: ': '.join(x), axis=1)

# invoke wt_avg function

wt_avg_2('PPREG4_core_par',
       ['DPES11', 'EPQ1', 'I10', 'IS1','IS6','IS8', 'L1','L4','L9','L11', 'MI9', 
        'SV3','SV8','SV11','SV12','SV16','SV17','SV18','SV21','TET7'])

wt_avg_2('PPREG4_PPEDUCAT',
       ['DPES11', 'EPQ1', 'I10', 'IS1','IS6','IS8', 'L1','L4','L9','L11', 'MI9', 
        'SV3','SV8','SV11','SV12','SV16','SV17','SV18','SV21','TET7'])

wt_avg_2('PPREG4_PPGENDER',
       ['DPES11', 'EPQ1', 'I10', 'IS1','IS6','IS8', 'L1','L4','L9','L11', 'MI9', 
        'SV3','SV8','SV11','SV12','SV16','SV17','SV18','SV21','TET7'])

wt_avg_2('PPREG4_PPINCCAT',
       ['DPES11', 'EPQ1', 'I10', 'IS1','IS6','IS8', 'L1','L4','L9','L11', 'MI9', 
        'SV3','SV8','SV11','SV12','SV16','SV17','SV18','SV21','TET7'])

--------------
cname: DPES11
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.466055
Midwest: Parent            0.575498
Northeast: Not Parent      0.468383
Northeast: Parent          0.550261
South: Not Parent          0.530309
South: Parent              0.436768
West: Not Parent           0.473113
West: Parent               0.502250
--------------
cname: EPQ1
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.241881
Midwest: Parent            0.270944
Northeast: Not Parent      0.255911
Northeast: Parent          0.262150
South: Not Parent          0.241441
South: Parent              0.288827
West: Not Parent           0.302075
West: Parent               0.261154
--------------
cname: I10
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.544183
Midwest: Parent            0.507011
Northeast: Not Parent      0.418660
Northeast: Parent          0.398765
South: Not Parent          0.502271
South: Parent              0.594648
West: Not Parent           0.427523
West: Parent               0.401548
--------------
cname: IS1
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.039193
Midwest: Parent            0.069254
Northeast: Not Parent      0.057089
Northeast: Parent          0.091341
South: Not Parent          0.063827
South: Parent              0.031649
West: Not Parent           0.070379
West: Parent               0.040766
--------------
cname: IS6
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.737362
Midwest: Parent            0.833985
Northeast: Not Parent      0.629298
Northeast: Parent          0.677853
South: Not Parent          0.687607
South: Parent              0.710120
West: Not Parent           0.690211
West: Parent               0.669246
--------------
cname: IS8
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.176614
Midwest: Parent            0.120218
Northeast: Not Parent      0.148563
Northeast: Parent          0.205161
South: Not Parent          0.131241
South: Parent              0.157513
West: Not Parent           0.144405
West: Parent               0.162739
--------------
cname: L1
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.082323
Midwest: Parent            0.057526
Northeast: Not Parent      0.091294
Northeast: Parent          0.034352
South: Not Parent          0.071029
South: Parent              0.049289
West: Not Parent           0.077620
West: Parent               0.043806
--------------
cname: L4
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.059512
Midwest: Parent            0.122727
Northeast: Not Parent      0.066792
Northeast: Parent          0.099098
South: Not Parent          0.055647
South: Parent              0.066095
West: Not Parent           0.067247
West: Parent               0.051984
--------------
cname: L9
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.051715
Midwest: Parent            0.024574
Northeast: Not Parent      0.025199
Northeast: Parent          0.004907
South: Not Parent          0.007225
South: Parent              0.010935
West: Not Parent           0.010880
West: Parent               0.011758
--------------
cname: L11
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.059640
Midwest: Parent            0.005027
Northeast: Not Parent      0.034090
Northeast: Parent          0.000000
South: Not Parent          0.017414
South: Parent              0.007905
West: Not Parent           0.028580
West: Parent               0.000000
--------------
cname: MI9
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.342251
Midwest: Parent            0.311478
Northeast: Not Parent      0.366839
Northeast: Parent          0.286687
South: Not Parent          0.342437
South: Parent              0.259772
West: Not Parent           0.257218
West: Parent               0.313889
--------------
cname: SV3
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.618158
Midwest: Parent            0.625875
Northeast: Not Parent      0.626896
Northeast: Parent          0.640019
South: Not Parent          0.648057
South: Parent              0.653844
West: Not Parent           0.583061
West: Parent               0.612939
--------------
cname: SV8
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.494030
Midwest: Parent            0.486596
Northeast: Not Parent      0.521721
Northeast: Parent          0.498180
South: Not Parent          0.520406
South: Parent              0.510535
West: Not Parent           0.542458
West: Parent               0.520685
--------------
cname: SV11
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.605813
Midwest: Parent            0.683762
Northeast: Not Parent      0.633608
Northeast: Parent          0.649517
South: Not Parent          0.642787
South: Parent              0.650910
West: Not Parent           0.593779
West: Parent               0.629969
--------------
cname: SV12
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.574291
Midwest: Parent            0.727590
Northeast: Not Parent      0.568442
Northeast: Parent          0.680308
South: Not Parent          0.557058
South: Parent              0.635272
West: Not Parent           0.499223
West: Parent               0.530344
--------------
cname: SV16
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.458168
Midwest: Parent            0.499158
Northeast: Not Parent      0.468984
Northeast: Parent          0.438816
South: Not Parent          0.458830
South: Parent              0.514568
West: Not Parent           0.389161
West: Parent               0.399307
--------------
cname: SV17
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.235925
Midwest: Parent            0.249856
Northeast: Not Parent      0.252412
Northeast: Parent          0.239829
South: Not Parent          0.216506
South: Parent              0.267284
West: Not Parent           0.177663
West: Parent               0.319209
--------------
cname: SV18
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.681769
Midwest: Parent            0.781486
Northeast: Not Parent      0.708031
Northeast: Parent          0.728035
South: Not Parent          0.655058
South: Parent              0.610774
West: Not Parent           0.598476
West: Parent               0.756174
--------------
cname: SV21
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.362674
Midwest: Parent            0.310528
Northeast: Not Parent      0.391601
Northeast: Parent          0.410480
South: Not Parent          0.324935
South: Parent              0.288753
West: Not Parent           0.346937
West: Parent               0.380445
--------------
cname: TET7
--------------
(8, 1)
<class 'pandas.core.frame.DataFrame'>
                       Weighted_Pct
Category
Midwest: Not Parent        0.728183
Midwest: Parent            0.696018
Northeast: Not Parent      0.697409
Northeast: Parent          0.868429
South: Not Parent          0.663901
South: Parent              0.690218
West: Not Parent           0.698610
West: Parent               0.700274
--------------
cname: DPES11
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.384615
Midwest: 12yrs          0.493097
Midwest: 12yrs+         0.543582
Midwest: 16yrs+         0.480677
Northeast: 11yrs-       0.245944
Northeast: 12yrs        0.456696
Northeast: 12yrs+       0.486880
Northeast: 16yrs+       0.563616
South: 11yrs-           0.448269
South: 12yrs            0.523450
South: 12yrs+           0.490037
South: 16yrs+           0.540637
West: 11yrs-            0.368139
West: 12yrs             0.575625
West: 12yrs+            0.477382
West: 16yrs+            0.433773
--------------
cname: EPQ1
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.297291
Midwest: 12yrs          0.215365
Midwest: 12yrs+         0.247493
Midwest: 16yrs+         0.259717
Northeast: 11yrs-       0.339390
Northeast: 12yrs        0.280402
Northeast: 12yrs+       0.177415
Northeast: 16yrs+       0.284615
South: 11yrs-           0.326005
South: 12yrs            0.289746
South: 12yrs+           0.266957
South: 16yrs+           0.149033
West: 11yrs-            0.344043
West: 12yrs             0.280331
West: 12yrs+            0.312978
West: 16yrs+            0.259287
--------------
cname: I10
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.406082
Midwest: 12yrs          0.507343
Midwest: 12yrs+         0.563476
Midwest: 16yrs+         0.600512
Northeast: 11yrs-       0.549643
Northeast: 12yrs        0.509784
Northeast: 12yrs+       0.368435
Northeast: 16yrs+       0.324729
South: 11yrs-           0.445277
South: 12yrs            0.467922
South: 12yrs+           0.530378
South: 16yrs+           0.644911
West: 11yrs-            0.432129
West: 12yrs             0.372038
West: 12yrs+            0.459547
West: 16yrs+            0.416821
--------------
cname: IS1
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.063506
Midwest: 12yrs          0.061123
Midwest: 12yrs+         0.057644
Midwest: 16yrs+         0.008048
Northeast: 11yrs-       0.000000
Northeast: 12yrs        0.034730
Northeast: 12yrs+       0.084727
Northeast: 16yrs+       0.093060
South: 11yrs-           0.104303
South: 12yrs            0.043955
South: 12yrs+           0.035076
South: 16yrs+           0.056104
West: 11yrs-            0.219545
West: 12yrs             0.081442
West: 12yrs+            0.018582
West: 16yrs+            0.042778
--------------
cname: IS6
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.648992
Midwest: 12yrs          0.727282
Midwest: 12yrs+         0.801236
Midwest: 16yrs+         0.798196
Northeast: 11yrs-       0.626866
Northeast: 12yrs        0.691528
Northeast: 12yrs+       0.548570
Northeast: 16yrs+       0.663421
South: 11yrs-           0.587706
South: 12yrs            0.712383
South: 12yrs+           0.726768
South: 16yrs+           0.709327
West: 11yrs-            0.710843
West: 12yrs             0.697712
West: 12yrs+            0.692803
West: 16yrs+            0.654044
--------------
cname: IS8
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.143113
Midwest: 12yrs          0.124946
Midwest: 12yrs+         0.209807
Midwest: 16yrs+         0.165386
Northeast: 11yrs-       0.000000
Northeast: 12yrs        0.132466
Northeast: 12yrs+       0.160416
Northeast: 16yrs+       0.222801
South: 11yrs-           0.122553
South: 12yrs            0.114349
South: 12yrs+           0.117115
South: 16yrs+           0.199958
West: 11yrs-            0.101071
West: 12yrs             0.127145
West: 12yrs+            0.097988
West: 16yrs+            0.239597
--------------
cname: L1
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.040027
Midwest: 12yrs          0.100021
Midwest: 12yrs+         0.036268
Midwest: 16yrs+         0.115714
Northeast: 11yrs-       0.374432
Northeast: 12yrs        0.062221
Northeast: 12yrs+       0.085537
Northeast: 16yrs+       0.037092
South: 11yrs-           0.021289
South: 12yrs            0.037778
South: 12yrs+           0.076801
South: 16yrs+           0.115877
West: 11yrs-            0.017738
West: 12yrs             0.062194
West: 12yrs+            0.084753
West: 16yrs+            0.066995
--------------
cname: L4
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.120304
Midwest: 12yrs          0.107975
Midwest: 12yrs+         0.056053
Midwest: 16yrs+         0.032298
Northeast: 11yrs-       0.335496
Northeast: 12yrs        0.050917
Northeast: 12yrs+       0.049649
Northeast: 16yrs+       0.074946
South: 11yrs-           0.022284
South: 12yrs            0.061031
South: 12yrs+           0.052405
South: 16yrs+           0.087539
West: 11yrs-            0.089395
West: 12yrs             0.035641
West: 12yrs+            0.068205
West: 16yrs+            0.074189
--------------
cname: L9
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.163238
Midwest: 12yrs          0.052818
Midwest: 12yrs+         0.021478
Midwest: 16yrs+         0.006460
Northeast: 11yrs-       0.104317
Northeast: 12yrs        0.033186
Northeast: 12yrs+       0.008095
Northeast: 16yrs+       0.003549
South: 11yrs-           0.000000
South: 12yrs            0.007976
South: 12yrs+           0.004856
South: 16yrs+           0.018103
West: 11yrs-            0.000000
West: 12yrs             0.016033
West: 12yrs+            0.003352
West: 16yrs+            0.017531
--------------
cname: L11
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.040027
Midwest: 12yrs          0.063446
Midwest: 12yrs+         0.026036
Midwest: 16yrs+         0.058837
Northeast: 11yrs-       0.133030
Northeast: 12yrs        0.038231
Northeast: 12yrs+       0.015073
Northeast: 16yrs+       0.003638
South: 11yrs-           0.052825
South: 12yrs            0.004411
South: 12yrs+           0.000000
South: 16yrs+           0.015929
West: 11yrs-            0.040161
West: 12yrs             0.034722
West: 12yrs+            0.016951
West: 16yrs+            0.003376
--------------
cname: MI9
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.274597
Midwest: 12yrs          0.268848
Midwest: 12yrs+         0.418293
Midwest: 16yrs+         0.345229
Northeast: 11yrs-       0.268008
Northeast: 12yrs        0.294744
Northeast: 12yrs+       0.391662
Northeast: 16yrs+       0.385599
South: 11yrs-           0.285175
South: 12yrs            0.306675
South: 12yrs+           0.327472
South: 16yrs+           0.352763
West: 11yrs-            0.077644
West: 12yrs             0.179739
West: 12yrs+            0.387400
West: 16yrs+            0.301624
--------------
cname: SV3
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.572227
Midwest: 12yrs          0.630028
Midwest: 12yrs+         0.586870
Midwest: 16yrs+         0.669605
Northeast: 11yrs-       0.807917
Northeast: 12yrs        0.594919
Northeast: 12yrs+       0.661225
Northeast: 16yrs+       0.611231
South: 11yrs-           0.708615
South: 12yrs            0.616441
South: 12yrs+           0.609198
South: 16yrs+           0.688892
West: 11yrs-            0.624658
West: 12yrs             0.563169
West: 12yrs+            0.591692
West: 16yrs+            0.609614
--------------
cname: SV8
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.361583
Midwest: 12yrs          0.462398
Midwest: 12yrs+         0.579227
Midwest: 16yrs+         0.494042
Northeast: 11yrs-       0.473718
Northeast: 12yrs        0.520382
Northeast: 12yrs+       0.466703
Northeast: 16yrs+       0.560738
South: 11yrs-           0.391265
South: 12yrs            0.500123
South: 12yrs+           0.546243
South: 16yrs+           0.597550
West: 11yrs-            0.621925
West: 12yrs             0.426646
West: 12yrs+            0.652571
West: 16yrs+            0.488821
--------------
cname: SV11
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.689401
Midwest: 12yrs          0.563035
Midwest: 12yrs+         0.629109
Midwest: 16yrs+         0.642165
Northeast: 11yrs-       0.786502
Northeast: 12yrs        0.582323
Northeast: 12yrs+       0.674582
Northeast: 16yrs+       0.639634
South: 11yrs-           0.712097
South: 12yrs            0.606929
South: 12yrs+           0.622176
South: 16yrs+           0.665841
West: 11yrs-            0.538438
West: 12yrs             0.657988
West: 12yrs+            0.616312
West: 16yrs+            0.566936
--------------
cname: SV12
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.585420
Midwest: 12yrs          0.604810
Midwest: 12yrs+         0.627063
Midwest: 16yrs+         0.601403
Northeast: 11yrs-       1.000000
Northeast: 12yrs        0.600339
Northeast: 12yrs+       0.529277
Northeast: 16yrs+       0.578027
South: 11yrs-           0.575507
South: 12yrs            0.600318
South: 12yrs+           0.553220
South: 16yrs+           0.580522
West: 11yrs-            0.617067
West: 12yrs             0.499945
West: 12yrs+            0.526349
West: 16yrs+            0.466598
--------------
cname: SV16
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.472719
Midwest: 12yrs          0.543901
Midwest: 12yrs+         0.392639
Midwest: 16yrs+         0.465642
Northeast: 11yrs-       0.410772
Northeast: 12yrs        0.462862
Northeast: 12yrs+       0.464029
Northeast: 16yrs+       0.468471
South: 11yrs-           0.492738
South: 12yrs            0.468257
South: 12yrs+           0.461645
South: 16yrs+           0.479983
West: 11yrs-            0.343869
West: 12yrs             0.473354
West: 12yrs+            0.427656
West: 16yrs+            0.298179
--------------
cname: SV17
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.172853
Midwest: 12yrs          0.278842
Midwest: 12yrs+         0.229021
Midwest: 16yrs+         0.241786
Northeast: 11yrs-       0.195977
Northeast: 12yrs        0.164893
Northeast: 12yrs+       0.309903
Northeast: 16yrs+       0.300917
South: 11yrs-           0.196379
South: 12yrs            0.261716
South: 12yrs+           0.271282
South: 16yrs+           0.173315
West: 11yrs-            0.385970
West: 12yrs             0.257922
West: 12yrs+            0.169696
West: 16yrs+            0.193763
--------------
cname: SV18
--------------
(16, 1)
<class 'pandas.core.frame.DataFrame'>
                    Weighted_Pct
Category
Midwest: 11yrs-         0.668605
Midwest: 12yrs          0.701841
Midwest: 12yrs+         0.733435
Midwest: 16yrs+         0.690960
Northeast: 11yrs-       0.625568
Northeast: 12yrs        0.661307
Northeast: 12yrs+       0.743524
Northeast: 16yrs+       0.757053
South: 11yrs-           0.663052

/Users/dschan/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py:2697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)